#ifndef GLOBALS_H
#define GLOBALS_H

#define USRN_LENGTH 32
#define GAME_ID_LENGTH 8
#define PASS_LENGTH 32
#define CHAR_LEN 32
#define GAME_LEN 32
#define MAX_GAME_USRCOUNT 6
#define MAX_GAMES 256
#define CNCTD_LST_LENGTH 2000
#define CLIENT_REQ_LEN 8192
#define SERVER_RSP_LEN 8192

#endif
