#ifndef GLOBALS_H
#define GLOBALS_H

#define USRN_LENGTH 32
#define GAME_ID_LENGTH 8
#define PASS_LENGTH 32
#define CHAR_LEN 32
#define GAME_LEN 32
#define MAX_GAME_USRCOUNT 6
#define MAX_GAMES 8
#define CNCTD_LST_LENGTH 200
#define CLIENT_REQ_LEN 65536
#define SERVER_RSP_LEN 65536

#define SCREEN_MAX_X 600
#define SCREEN_MAX_Y 400

#define PROJ_COUNT_PLAYER 64
#define BACKOFF_TICKS 60

#endif
